build [0.97.420.462.3]

diff --git a/entities.install b/entities.install
--- a/entities.install
+++ b/entities.install
@@ -4,17 +4,21 @@
 	[[ "${_u:0:12}" < 'Ubuntu 16.04' ]] \
 			&& msg.die 'entities.bash requires Ubuntu 16.04 or higher.'
 	unset _u
+
 usage() {
-	local v
+	local v PRG
+	PRG=$(basename "$0")
 	v="$(dirname "$(readlink "$0")")/entities.d/entities.version.bash"
 	# shellcheck disable=2015
 	[[ -f "$v" ]] && source "$v" 2>/dev/null || true	# yes, this is deliberate
 	cat <<-etx
-	Script  : $(basename "$0")
-	Version : ${_ent_VERSION:-Not Found}
+	Script  : $PRG
+	Version : ${_ent_VERSION:-Version Not Found}
 	Desc    : entities.bash installation program.
 	        : Requires root to install.
-	Synopsis: $(basename "$0") [-y] [-i] [-u] [-c] [-l] [-p] [-v|-q] [-V] [-h]
+	        : Dependencies are defined in 
+	        : [$PRGDIR/docs/entities.external.dependencies.list]
+	Synopsis: $PRG [-y][-i] [-u][-c][-l] [-p] [-v][-q] [-V] [-h]
 	        :   -y|--auto         install without prompting.
 	        :   -i|--install      install with prompt.
 	        :   -u|--apt-upgrade  before external dependencies are installed
@@ -23,14 +27,16 @@ usage() {
 	        :                     perform apt autoremove and apt clean.
 	        :   -l|--mlocate      update mlocate database. (This could take
 	        :                     some time.)
-	        :   -p|--prod         make new build of help files and increment 
+	        :   -p|--prod         make new build of help files and increment
 	        :                     version build numbers (for developers).
 	        :   -v|--verbose      turn message verbose on. Default on.
 	        :   -q|--quiet        turn message verbose off. Default off.
 	        :   -V|--version      print entities.bash version.
 	        :   -h|--help         print help message.
-	Examples: 0. $PRG -y          # just install it.
-	        : 1. $PRG -y -u -c -l # do everything.
+	Examples: # 0. Just install it.
+	        : $PRG -y
+	        : # 1. Do everything.
+	        : $PRG -y -u -c -l
 	etx
 	((EUID)) && echo >&2 "        : Current user is [${EUID:-} ${USER:-}]"
 	exit "${1:-0}"
@@ -42,12 +48,12 @@ usage() {
 
 	declare -ix MajorVer=1 MinorVer=0
 
-	declare -i production=0
-	declare -i autoinstall=0
-	declare -i install=0
+	declare -i Production=0
+	declare -i autoInstall=0
+	declare -i Install=0
 	declare -i AptUpgrade=0 AptClean=0 MLocate=0
 	declare canonical
-	
+
 	declare etc_profile_d='/etc/profile.d/entities.env.sh'
 
 	# make absolutely certain we have identified the canonical entities.bash script
@@ -59,10 +65,10 @@ usage() {
 		echo >&2 "$PRG: Could not find entities.bash in the [$PRGDIR] directory."
 		echo >&2 "$PRG: Check that it has been installed properly."
 		exit 2
-	fi	
+	fi
 	OPRG=$PRG; OPRGDIR=$PRGDIR
-	
-	OENTITIES=${ENTITIES:-}; ENTITIES=$PRGDIR 
+
+	OENTITIES=${ENTITIES:-}; ENTITIES=$PRGDIR
 	source "$canonical" new || { echo >&2 "$PRG: Could not open [$canonical]!"; exit 2; }
 	ENTITIES=$OENTITIES;
 	PRG=$OPRG; PRGDIR=$OPRGDIR
@@ -80,14 +86,14 @@ usage() {
 	# 	ENTITIES in this case is the destination directory for the install
 	ENTITIES='/lib/include/entities'
 	mkdir -p "$ENTITIES" || exit 2
-	
+
 	# are we trying to install into the install directory?
 	[[ $ENTITIES == "$PRGDIR" ]] &&	msg.die 'Cannot install over installation directory!'
 
 	declare env_entities
 	# shellcheck disable=SC2154
 	env_entities="$(cat <<-eot
-	
+
 			#X entities.bash begin
 			#X entities $_ent_VERSION
 			#X   * export ENTITIES='${ENTITIES}'
@@ -102,72 +108,73 @@ usage() {
 		)"
 
 	# Exclusions for rsync
-	declare -a exclude=( 't' 'tt' '*~' '*.bak' '*.old' 'gudang/' '.gudang/' '*.zip' 'dev/' 'test/' 'tmp/' 'temp/' )
+	declare -a exclude=( 't' 'tt' 't1' 't2' '*~' '*.bak' '*.old' 'gudang/' '.gudang/' '*.zip' 'dev/' 'test/' 'tmp/' 'temp/' )
 	declare SyncExclude="/tmp/$PRG-exclusions-$RANDOM"
 	>"$SyncExclude"
 	declare _l; for _l in "${exclude[@]}"; do	echo "${_l}"; done >>"$SyncExclude"; unset _l
-			
+		
 main() {
 	declare _verfile="$PRGDIR/entities.d/entities.version.bash"
 	source "$_verfile" || msg.die "Could not source [$_verfile]"
 	while (( $# )); do
 		case "$1" in
-			--dev|-p|--prod*)	production=1;;
-			-y|--auto)				autoinstall=1; install=1;;
-			-i|--install)			install=1;;
+			-p|--prod*)				Production=1;;
+			-y|--auto)				autoInstall=1; Install=1;;
+			-i|--install)			Install=1;;
 			-u|--apt-upgrade)	AptUpgrade=1;;
 			-c|--apt-clean)		AptClean=1;;
 			-l|--mlocate)			MLocate=1;;
-			-v|--verbose)			verbose.set on;;
-			-q|--quiet)				verbose.set off;;
+			-v|--verbose|+q)	verbose.set on;;
+			-q|--quiet|+v)		verbose.set off;;
 			-V|--version)			echo "$PRG ${_ent_VERSION}"; return 0;;
 			-h|--help)				usage 0;;
 			*)								msg.die "Bad command argument [$1]";;
 		esac
 		shift
 	done
-	(( ! install )) && usage 1 
-	
+	(( ! Install )) && usage 1
+
 	msg.info "Installation directory is [$canonical]"
 	msg.info "entities.bash shall be installed to [$ENTITIES]."
 	if [[ -f "$ENTITIES/entities.bash" ]]; then
 		msg.warn "entities.bash is already installed at [$ENTITIES]."
 		msg.warn "Backup will be at [$ENTITIES/entities.bash.old]."
 	fi
-	
-	if (( ! autoinstall)); then
+
+	if (( ! autoInstall)); then
 		infotext
 		ask.yn 'Install with these settings?' \
 				|| { echo; return 0; }
-		msg 'Installing entities.bash'
 	fi
 
-	if ((production)); then
-		msg.info "Creating Help Files"
+	msg 'Installing entities.bash'
+
+	if ((Production)); then
+		msg.info 'Creating Help Files'
 		"$PRGDIR/entities.help.make" --auto	|| msg.die "[$PRGDIR/entities.help.make] failed!"
-		# make new version file
+		msg.info 'Create new entities.bash version/build file'
 		[[ -z ${_ent_VERSION:-} ]] && msg.die "Version has not been set. See [$_verfile]"
 		declare -ia _arr
 		_arr=( ${_ent_VERSION//./ } )
 		declare -i _dayssince
 		_dayssince=$(( ($(date +%s) - $(date +%s -d '2019-06-21')) / (60*60*24) ))
 		_arr[2]=420
-		(( _arr[3] == _dayssince )) || { _arr[3]=${_dayssince}; _arr[4]=0; } 
+		(( _arr[3] == _dayssince )) || { _arr[3]=${_dayssince}; _arr[4]=0; }
 		_arr[4]+=1
 		_p=${_arr[*]}
 		cat >"$_verfile" <<-etx
 			#!$(which bash)
-			#X Global   : _ent_VERSION 
-			#X Desc     : Return version/build of this entities.bash.
-			#X          : Returns string in form:
-			#X          :   majorver.minorver.420.day0.build
-			#X          : Where:
-			#X          :   majorver  ${MajorVer}
-			#X          :   minorver  ${MinorVer}
-			#X          :   420       constant
-			#X          :   day0      days since 2019-06-21 ($_dayssince)
-			#X          :   build     this is build #${_arr[4]} on day $_dayssince
-			#X          : This is entities.bash version ${_p// /.}
+			#X Global: _ent_VERSION
+			#X Desc  : Return version/build of this entities.bash.
+			#X       : Returns string in form:
+			#X       :   majorver.minorver.420.day0.build
+			#X       : Where:
+			#X       :   majorver  ${MajorVer}
+			#X       :   minorver  ${MinorVer}
+			#X       :   420       constant
+			#X       :   day0      days since 2019-06-21 ($_dayssince)
+			#X       :   build     this is build #${_arr[4]} on day $_dayssince
+			#X       : This is entities.bash version ${_p// /.}
 			declare -xg _ent_VERSION
 			_ent_VERSION='${_p// /.}'
 			#fin
@@ -184,14 +191,13 @@ main() {
 	makeenvirnonment
 
 	install
-	
+
 	install_externals || true
 
 	testit
 
 	msg.line '-'
 	msg "entities.bash [${_ent_VERSION}] has been installed." \
-			'Exit from this bash session and then re-enter.' \
 			'To activate entities.bash environment enter:' \
 			'    source entities new' \
 			'For help:' \
@@ -204,7 +210,7 @@ main() {
 makeprofile() {
 	msg.info "Creating [${etc_profile_d}]"
 	mkdir -p "$(dirname "$etc_profile_d")" || msg.die "Could not create [$(dirname "$etc_profile_d")]"
-	echo -e "${env_entities}"	> "$etc_profile_d"			
+	echo -e "${env_entities}"	> "$etc_profile_d"		
 	chmod 644 "$etc_profile_d" 				|| msg.die "Could not chmod 644 [$etc_profile_d]"
 	chown root:root "$etc_profile_d"	|| msg.die "Could not chown [$etc_profile_d]"
 }
@@ -215,7 +221,7 @@ makeenvirnonment() {
 	msg.info "Modifying [$envfile]"
 	tmpfile="$(mktemp --tmpdir 'ent-XXXX')"
 	grep -v '^[[:blank:]]*ENTITIES=' "$envfile" >"$tmpfile" || true
-	echo "ENTITIES=\"$ENTITIES\"" >> "$tmpfile" 
+	echo "ENTITIES=\"$ENTITIES\"" >> "$tmpfile"
 	cp -p "$envfile" "${envfile}~"	|| msg.die "Could not backup [$envfile] to [${envfile}~]"
 	chown root:root "$tmpfile"			|| msg.die "[$tmpfile] chown error!"
 	chmod 644 "$tmpfile" 						|| msg.die "[$tmpfile] chmod error!"
@@ -225,14 +231,24 @@ makeenvirnonment() {
 
 infotext() {
 	tab.set ++
-	msg \
-		"This entities.bash installation script shall do the following: " \
-		"  * Copy all script files to directory [$ENTITIES]" \
-		"  * Add path [$ENTITIES] to [$etc_profile_d]" 		\
-		"  * Add path [$ENTITIES] to [/etc/environment]" \
-		"ENTITIES=[$ENTITIES]" \
-		"PRG=[$PRG]" 					\
-		"PRGDIR=[$PRGDIR]"
+	msg "entities.bash installation shall:"
+	((Production)) && \
+	msg "  * Create Help Files" \
+			"  * Create new entities.bash version/build"
+	msg	"  * Create [$etc_profile_d]" \
+			"  * Add envvar ENTITIES [$ENTITIES] to [/etc/environment]" \
+			"  * Copy all script files to directory [$ENTITIES]" \
+			"  * Install external dependencies"
+	((AptUpgrade)) && \
+	msg "  * Run apt-get update/upgrade"
+	((AptClean)) && \
+	msg "  * Run apt-get autoremove/clean"
+	((MLocate)) && \
+	msg "  * Run updatedb"
+
+#	msg	"ENTITIES=[$ENTITIES]" \
+#			"PRG=[$PRG]" 					\
+#			"PRGDIR=[$PRGDIR]"
 	tab.set --
 }
 
@@ -241,13 +257,13 @@ install() {
 	msg.info "Installing Entities to [${ENTITIES}]"
 
 	cd "$PRGDIR" || exit 2
-	
+
 	# do backup of existing $ENTITIES directory
 	msg.info "Backing up [$ENTITIES]"
 	if [[ -d "${ENTITIES}.old" ]]; then
 		if [[ -d "${ENTITIES}" ]]; then
 			msg.info "* Deleting [$ENTITIES.old]"
-			rm -rf "${ENTITIES}.old"	
+			rm -rf "${ENTITIES}.old"
 		fi
 	fi
 	if [[ -d "${ENTITIES}" ]]; then
@@ -260,14 +276,15 @@ install() {
 	mkdir -p "$ENTITIES" || exit $?
 	[[ -d "$ENTITIES" ]] || exit $?
 
-	/usr/bin/rsync -a  --exclude-from "$SyncExclude" entities.bash 			"$ENTITIES/" >/dev/null || exit $?
-	/usr/bin/rsync -a  --exclude-from "$SyncExclude" entities.bash.min  "$ENTITIES/" >/dev/null || exit $?
-	/usr/bin/rsync -a  --exclude-from "$SyncExclude" entities.help      "$ENTITIES/" >/dev/null || exit $?
-	/usr/bin/rsync -a  --exclude-from "$SyncExclude" entities.help.make "$ENTITIES/" >/dev/null || exit $?
+	/usr/bin/rsync -a entities.bash					"$ENTITIES/" >/dev/null || exit $?
+	/usr/bin/rsync -a entities.bash.min			"$ENTITIES/" >/dev/null || exit $?
+	/usr/bin/rsync -a entities.make.minimal	"$ENTITIES/" >/dev/null || exit $?
+	/usr/bin/rsync -a entities.help					"$ENTITIES/" >/dev/null || exit $?
+	/usr/bin/rsync -a entities.help.make		"$ENTITIES/" >/dev/null || exit $?
 
-	cp -p LICENSE  "$ENTITIES/" || exit $?
+	cp -p LICENSE "$ENTITIES/" || exit $?
 	( echo "##### Version [$_ent_VERSION]"
-		grep -iv '^#####[[:blank:]]version[[:blank:]]\[' README.md 
+		grep -iv '^#####[[:blank:]]version[[:blank:]]\[' README.md
 	) > "$ENTITIES/README.md"
 	cp -p "$ENTITIES/README.md" README.md || exit $?	# yes, other way around; saves using a temp file
 
@@ -283,12 +300,12 @@ install() {
 	# make symlinks in $ENTITIES directory
 	msg.info "Creating symlinks in [$ENTITIES] directory"
 	cd "$ENTITIES" 																|| exit 2
-	# execute permissions on entities	
+	# execute permissions on entities
 	chmod 775 entities.bash entities.bash.min			|| exit $?
 	# in production, entities points to the min version
-	ln  -fs entities.bash.min entities				    || exit $?
-	ln  -fs entities.bash.min entities.min		    || exit $?
-	
+	ln -fs entities.bash.min entities						|| exit $?
+	ln -fs entities.bash.min entities.min				|| exit $?
+
 	# MAIN EXECUTABLE in /usr/local/bin/ || /usr/bin
 	if [[ -d /usr/local/bin ]]; then
 		ln -fs "$ENTITIES/entities.bash" /usr/local/bin/entities || exit $?
@@ -300,7 +317,7 @@ install() {
 	declare -a arr
 	declare -- s
 	arr=( $(find scripts/ -maxdepth 1 -executable -type f) )
-	for s in "${arr[@]}"; do 
+	for s in "${arr[@]}"; do
 		s=$(basename "$s")
 		if [[ $HOSTNAME == 'okusi0' ]]; then
 			msg.info "Linking $PRGDIR/scripts/$s to /usr/local/bin/$s"
@@ -309,35 +326,36 @@ install() {
 			msg.info "Linking $ENTITIES/scripts/$s to /usr/local/bin/$s"
 			ln -fs "$ENTITIES/scripts/$s" "/usr/local/bin/$s"
 		fi
-	done 
-	
+	done
+
 	# touch420 all files in $ENTITIES directory
 	msg.info "Change permissions in [$ENTITIES] directory"
 	cd "$ENTITIES" || exit 2
 	chown root:root ${ENTITIES}/* -R
-	declare IFS=$'\n'
-	for f in $(/usr/bin/find | grep -v ".g"); do 
+	local IFS=$'\n'
+	for f in $(/usr/bin/find | grep -v ".g"); do
 		if [[ -d "$f" ]]; then
 			chmod 775 "$f"
-		else 
+		else
 			chmod u+rw,g+rw,o+rw "$f"	#should this be 555?? ###
 		fi
 		fd=$(stat "$f" -c '%y');
-		fd=${fd%% *} 
+		fd=${fd%% *}
 		/usr/bin/touch -h -d "$(date +'%F 04:20:00' -d "$fd")" "$f"
 	done
 
-	# back to base	
+	# back to base
 	cd "$PRGDIR"
 }
 
+# test installation
 testit() {
-		# test it
-		cd "$ENTITIES" || { echo >&2 "wtf? Could not change to [$ENTITIES]"; return 1; } 
-		strict.set off
-		trap.set off
-		source entities.bash new || { echo >&2 "wtf?? Could not source [$PWD/entities.bash]"; return 1; }
-		trap.set on
+	cd "$ENTITIES" || { echo >&2 "wtf? Could not change to [$ENTITIES]"; return 1; }
+	strict.set off
+	trap.set off
+	source ./entities.bash new || { echo >&2 "wtf?? Could not source [$PWD/entities.bash]"; return 1; }
+	trap.set on
+	return 0
 }
 
 make.syncexclude() {
@@ -374,29 +392,22 @@ make.syncexclude() {
 }
 
 install_externals() {
+	declare -a _ent_ESSENTIAL_PACKAGES=()
+	declare -a _ent_RECOMMENDED_PACKAGES=()
+	declare -a _ent_PHP_MYSQL_CLIENT_PACKAGES=()
+	source "$PRGDIR/docs/entities.external-dependencies.list" \
+			|| { msg.err "Dependencies file not found."; return 2; }
+
 	# update/upgrade
-	msg.info "Updating Installed Packages"
 	if ((AptUpgrade)); then
-		apt-get --yes  update 	|| msg.die 'Error updating packages.'
-		apt-get --yes  upgrade	|| msg.die 'Error upgrading packages.'
+		msg.info "Updating Installed Packages"
+		apt-get --yes update 	|| msg.die 'Error updating packages.'
+		apt-get --yes upgrade	|| msg.die 'Error upgrading packages.'
 	fi
-	
+
 	msg.info "Installing External Dependencies"
-	apt-get install --yes \
-			errno							\
-			git								\
-			gzip							\
-      hexedit           \
-      joe               \
-      lynx 							\
-			moreutils					\
-      nmap              \
-			shellcheck				\
-			tree							\
-      unzip 						\
-      w3m 			        \
-			wget              \
-      zip								\
+	# shellcheck disable=2068
+	apt-get install --yes ${_ent_ESSENTIAL_PACKAGES[@]} ${_ent_RECOMMENDED_PACKAGES[@]} ${_ent_PHP_MYSQL_CLIENT_PACKAGES[@]} \
 			||	msg.err "Error/s installing external dependencies."
 
 	if ((AptClean)); then
@@ -408,7 +419,7 @@ install_externals() {
 		msg.info "Updating mlocate Database"
 		updatedb || true
 	fi
-		
+	
 	msg.info "All external packages installed."
 	return 0
 }
