build [0.97.420.463.15]

diff --git a/scripts/dbh b/scripts/dbh
--- a/scripts/dbh
+++ b/scripts/dbh
@@ -8,20 +8,23 @@
 #X Depends :
 #X See Also:
 source "$OKROOT/entities/entities.bash" new || exit 2
-	version.set '0.97'
+	version.set '0.98'
 	verbose.set on
 	trap.set on
 	strict.set on
+	tab.width 8
+	tabs 8			# for the select builtin
 	msg.prefix.set "$PRG"
 	msg.prefix.separator.set '> '
 	
-	declare -xg Profile='' ProfileStr=''
-	declare -xg Database='' DataTable='' DataCommand=''
-
+	declare -xg Profile='' Database='' DataTable='' DataCommand=''
+	
+	declare -xrg Profile_Default=/root/.my.cnf
+	 
 main() {
 	while (( $# )); do
 		case "$1" in
-			-p|--profile)	shift; Profile="$1";;
+			-p|--profile)	shift; Profile="${1:-}";;
 			-V|--version)	echo "$PRG $(version.set)"; return 0;;
 			-h|--help)		usage; return 0;;
 			-?|--*)				msg.err "Invalid option [$1]"; return 1;;
@@ -37,13 +40,10 @@ main() {
 		shift
 	done
 	[[ -z $DataCommand && -n $DataTable ]] && DataCommand='fields'
-
-	if [[ -n $Profile ]]; then
-		[[ -f $Profile ]] || { msg.err "Profile [$Profile] not found."; return 2; }
-		ProfileStr="--defaults-extra-file=$Profile"
-	fi
-		
-	tabs 8	
+	[[ -z $Profile ]] && Profile=$Profile_Default
+	[[ -f $Profile ]] || { msg.err "Profile [$Profile] not found."; return 2; }
+	msg "Using profile [$Profile]"
+	msg "Select 0 to backup up, q to quit."		
 	while ((1)); do
 		msg.prefix.set "$PRG"
 		[[ -n $Database ]] || select_database
@@ -68,7 +68,7 @@ select_database() {
 	msg.prefix.set ++ 'Databases'
 	PS3="$(msg.prefix.set)Select Database: "
 	echo
-	select v in $(mysql $ProfileStr --no-auto-rehash -Nse 'show databases;' | sort -i); do 
+	select v in $(mysql --defaults-file="$Profile" --no-auto-rehash -Nse 'show databases;' | sort -i); do 
 		[[ $REPLY == 'q' ]] && exit 0
 		[[ $REPLY == '0' ]] && { v=''; break; }
 		[[ -z $v ]] && continue
@@ -83,7 +83,7 @@ select_table() {
 	msg.prefix.set ++ "$Database"
 	PS3="$(msg.prefix.set)Select Table: "
 	echo
-	select v in $(mysql $ProfileStr --no-auto-rehash -Nse "use $Database; show tables;" | sort -i); do 
+	select v in $(mysql --defaults-file=$Profile --no-auto-rehash -Nse "use $Database; show tables;" | sort -i); do 
 		[[ $REPLY == 'q' ]] && exit 0
 		[[ $REPLY == '0' ]] && { v=''; break; }
 		[[ -z $v ]] && continue
@@ -94,7 +94,12 @@ select_table() {
 }
 
 select_command() {
-	local v REPLY PS3
+	local v REPLY PS3 sx
+	
+	sx=$(mysql --defaults-file=$Profile --no-auto-rehash \
+						-Nse "SELECT count(*) FROM $Database.$DataTable") 
+	msg "[$sx] rows in [$Database.$DataTable]"
+	
 	msg.prefix.set ++ "$Database:$DataTable"
 	PS3="$(msg.prefix.set)Select Command: "
 	local -a cmds
@@ -117,7 +122,7 @@ select_command() {
 }
 
 do_structure() {
-	mysql $ProfileStr --prompt="$(msg.prefix.set)" --no-auto-rehash  "$Database" -e "show columns from $DataTable" || true
+	mysql --defaults-file=$Profile --prompt="$(msg.prefix.set)" --no-auto-rehash  "$Database" -e "show columns from $DataTable" || true
 	return 0
 }
 
@@ -128,7 +133,7 @@ do_command() {
 	while((1)); do
 		read -e -r -p "$PS3" cmd
 		[[ -z $cmd || $cmd == '0' || $cmd == 'q' ]] && break
-		mysql $ProfileStr --no-auto-rehash "$Database" -e "$cmd" || true
+		mysql --defaults-file=$Profile --no-auto-rehash "$Database" -e "$cmd" || true
 	done
 	msg.prefix.set --
 	return 0
@@ -137,7 +142,7 @@ do_command() {
 do_prompt() {
 	msg.prefix.set '++' "$Database"
 	(
-		mysql $ProfileStr --no-auto-rehash --prompt="$(msg.prefix.set)mysql> " "$Database"	
+		mysql --defaults-file=$Profile --no-auto-rehash --prompt="$(msg.prefix.set)mysql> " "$Database"	
 	) || true
 	msg.prefix.set --
 	return 0
@@ -165,7 +170,7 @@ do_select() {
 								$([[ -n $morder ]] && echo "ORDER BY $morder")  \
 								$([[ -n $mlimit ]] && echo "LIMIT $mlimit")"
 			msg "$(remsp2 "$selectstr")"
-			mysql $ProfileStr --no-auto-rehash "$Database" -e "$selectstr" || perror $?
+			mysql --defaults-file=$Profile --no-auto-rehash "$Database" -e "$selectstr" || perror $?
 		) || true
 	done
 	msg.prefix.set --
@@ -183,7 +188,7 @@ do_fields() {
 	fi
 	msg.prefix.set ++ "$db:$table"
 	msg.info 'Fields: '
-	flds=( $(mysql $ProfileStr -Nse "use information_schema; 
+	flds=( $(mysql --defaults-file=$Profile -Nse "use information_schema; 
 							SELECT concat(COLUMN_NAME,'~',replace(COLUMN_TYPE,' ','~')) FROM COLUMNS 
 									WHERE TABLE_SCHEMA='$db' AND TABLE_NAME='$table';") )
 	for fld in "${flds[@]}"; do
