build [0.97.420.465.11]

diff --git a/scripts/dbh b/scripts/dbh
--- a/scripts/dbh
+++ b/scripts/dbh
@@ -1,14 +1,9 @@
 #!/bin/bash
-#! shellcheck disable=SC2086
-#X Function|Global|Local|Script: 
-#X Desc    : 
-#X Synopsis: 
-#X Options :
-#X Example : 
-#X Depends :
-#X See Also:
+#! shellcheck disable=SC2154
+#X Script  : dbh 
+#X Desc    : See dbh --help
 source "$OKROOT/entities/entities.bash" new || exit 2
-	version.set '0.98'
+	version.set "${_ent_VERSION}"
 	verbose.set on
 	trap.set on
 	strict.set on
@@ -23,7 +18,7 @@ main() {
 	while (( $# )); do
 		case "$1" in
 			-p|--profile)	shift; Profile="${1:-}";;
-			-V|--version)	echo "$PRG $(version.set)"; return 0;;
+			-V|--version)	echo "entities.bash $(version.set)"; return 0;;
 			-h|--help)		usage; return 0;;
 			-?|--*)				msg.err "Invalid option [$1]"; return 1;;
 			*)						if   [[ -z $Database ]]; 	  then Database="$1"
@@ -37,7 +32,7 @@ main() {
 		esac
 		shift
 	done
-	[[ -z $DataCommand && -n $DataTable ]] && DataCommand='fields'
+	[[ -z $DataCommand && -n $DataTable ]] && DataCommand='columns'
 	[[ -z $Profile ]] && Profile=$Profile_Default
 	[[ -f $Profile ]] || { msg.err "Profile [$Profile] not found."; return 2; }
 
@@ -56,7 +51,11 @@ main() {
 			while ((1)); do
 				[[ -n $DataCommand ]] || select_command
 				[[ -z $DataCommand ]] && break
-				"do_${DataCommand}"
+				if ! type -t "do_${DataCommand}" &>/dev/null; then
+					msg.err "Command $DataCommand not found."
+				else
+					"do_${DataCommand}" || true
+				fi
 				DataCommand=''
 			done
 			DataTable=''
@@ -70,6 +69,7 @@ select_database() {
 	msg.prefix.set ++ 'Databases'
 	PS3="$(msg.prefix.set)Select Database: "
 	echo
+	tabs 8
 	select v in $(mysql --defaults-file="$Profile" --no-auto-rehash -Nse 'show databases;' | sort -i); do 
 		[[ $REPLY == 'q' ]] && exit 0
 		[[ $REPLY == '0' ]] && { v=''; break; }
@@ -85,6 +85,7 @@ select_table() {
 	msg.prefix.set ++ "$Database"
 	PS3="$(msg.prefix.set)Select Table: "
 	echo
+	tabs 8
 	select v in $(mysql --defaults-file=$Profile --no-auto-rehash -Nse "use $Database; show tables;" | sort -i); do 
 		[[ $REPLY == 'q' ]] && exit 0
 		[[ $REPLY == '0' ]] && { v=''; break; }
@@ -99,19 +100,20 @@ select_command() {
 	local v REPLY PS3 sx
 	
 	sx=$(mysql --defaults-file=$Profile --no-auto-rehash \
-						-Nse "SELECT count(*) FROM $Database.$DataTable") 
+						-Nse "SELECT count(*) FROM $Database.$DataTable")  || perror $?
 	msg "[$sx] rows in [$Database.$DataTable]"
 	
 	msg.prefix.set ++ "$Database:$DataTable"
 	PS3="$(msg.prefix.set)Select Command: "
 	local -a cmds
 	cmds=(	'structure' 
-					'fields'
-					'select'
-					'command'
-					'prompt' 
+					'columns'
+					'select_fields'
+					'sql_command'
+					'sql_prompt' 
 					''
 			 )
+	tabs 8
 	echo
 	select v in "${cmds[@]}"; do 
 		[[ $REPLY == 'q' ]] && exit 0
@@ -124,33 +126,31 @@ select_command() {
 }
 
 do_structure() {
-	mysql --defaults-file=$Profile --prompt="$(msg.prefix.set)" --no-auto-rehash  "$Database" -e "show columns from $DataTable" || true
+	mysql --defaults-file=$Profile --prompt="$(msg.prefix.set)" --no-auto-rehash  "$Database" -e "show columns from $DataTable" || perror $?
 	return 0
 }
 
-do_command() {
+do_sql_command() {
 	local cmd='' PS3
 	msg.prefix.set ++ "$Database:$DataTable"
-	PS3="$(msg.prefix.set)Command: "
+	PS3="$(msg.prefix.set)mysql> "
 	while((1)); do
 		read -e -r -p "$PS3" cmd
 		[[ -z $cmd || $cmd == '0' || $cmd == 'q' ]] && break
-		mysql --defaults-file=$Profile --no-auto-rehash "$Database" -e "$cmd" || true
+		mysql --defaults-file=$Profile --no-auto-rehash "$Database" -e "$cmd" || perror $?
 	done
-	msg.prefix.set --
+	msg.prefix.set '--'
 	return 0
 }
 
-do_prompt() {
+do_sql_prompt() {
 	msg.prefix.set '++' "$Database"
-	(
-		mysql --defaults-file=$Profile --no-auto-rehash --prompt="$(msg.prefix.set)mysql> " "$Database"	
-	) || true
+	(mysql --defaults-file=$Profile --no-auto-rehash --prompt="$(msg.prefix.set)mysql> " "$Database"	|| perror $?) || true
 	msg.prefix.set --
 	return 0
 }
 
-do_select() {
+do_select_fields() {
 	local mselect='*' mwhere='' mlimit='100' morder='' PS3
 	msg.prefix.set ++ "$Database:$DataTable"
 	PS3="$(msg.prefix.set)Select: "
@@ -176,10 +176,12 @@ do_select() {
 		) || true
 	done
 	msg.prefix.set --
+	tabs 8
 	return 0
 }
 
-do_fields() {
+	do_fields() { do_columns "$@"; }
+do_columns() {
 	local -a flds
 	local fld
 	local db="$Database" table="$DataTable" 
@@ -214,17 +216,25 @@ usage() {
 	Desc    : MySQL helper script to quickly view data/structure/info, 
 	        : without a lot of typing long sql commands. Fast in, fast out.
 	Synopsis: $PRG [database [table [command]]] [-p profile] [-V] [-h]
-	        :   -p|--profile  Specify mysql profile [eg, /root/.my3.cnf].
+	        :   database      Database name.
+	        :   table         Table name.
+	        :   command       Valid commands are:
+	        :                   columns select_fields sql_command 
+	        :                   sql_prompt structure
+	        :   -p|--profile  Specify MySQL profile [eg, /root/.my3.cnf].
 	        :   -V|--version  Print version.
 	        :   -h|--help     This help.
-	        : To back out of a menu, select 0.
-	        : To exit, select q.
-	Examples: # 0. go direct to database selection menu.
+	        : To back out of a menu, select 0. To exit, select q.
+	Examples: 
+	        : # 0. go direct to database selection menu.
 	        : $PRG
+	        :
 	        : # 1. open db Users, then to table selection.
 	        : $PRG Users
-	        : # 2. open table Users:user and show fields.
-	        : $PRG Users users fields 
+	        :
+	        : # 2. open table Users:user and show column names.
+	        : $PRG Users users columns 
+	        :
 	        : # 3. open mysql with profile, open Essays:essays 
 	        : $PRG -p /root/my3.cnf Essays essays
 	usage
