build [0.97.420.461.24]

diff --git a/scripts/p b/scripts/p
--- a/scripts/p
+++ b/scripts/p
@@ -1,18 +1,17 @@
 #!/bin/bash
 ##!	shellcheck disable=SC2086
-	source entities || { echo >&2 "$(basename "$"): Could not open entities.bash!"; exit 1; }
-#	source $OKROOT/entities/entities.bash new || { echo >&2 "Could not open entities.bash!"; exit 1; }
-#	source entities.bash new || { echo >&2 "Could not open entities.bash!"; exit 1; }
+source entities || { echo >&2 "$(basename "$0"): Could not open entities.bash!"; exit 1; }
 	strict.set off
 	verbose.set on
 	trap.set on
 	
-	# if by some chance entities.bash has not already set EDITOR
+	# if by some odd chance entities.bash has not already set EDITOR (it should have)
 	if [[ -z "$EDITOR" ]]; then
-		EDITOR="$(which joe) -tab 2 --wordwrap --autoindent"
+		EDITOR="$(which joe)" #mefirst
+		[[ -n "$EDITOR" ]] && EDITOR+=' -tab 2 --wordwrap --autoindent'
 		[[ -z "$EDITOR" ]] &&	EDITOR="$(which nano)"
 		[[ -z "$EDITOR" ]] &&	EDITOR="$(which vi)"
-		[[ -z "$EDITOR" ]] && echo >&2 "$(basename "$"): envvar EDITOR not set!"
+		[[ -z "$EDITOR" ]] && { echo >&2 "$(basename "$"): envvar EDITOR not set!"; exit 1; }
 	fi
 	export EDITOR
 	
@@ -39,41 +38,55 @@ main() {
 	done
 	(( ${#cmd[@]} == 1 )) || { usage; return 0; }
 
-	file="$(readlink -f "${cmd[0]}")"
-	[[ -f $file ]] || file="$(readlink -f "$(which "${cmd[0]:-}")")"
+	file="$(readlink -f "${cmd[0]}")" || file="${cmd[0]}"
 	
-	if [[ ! -f "${file}" ]]; then
-		if [[ -f "${file}.php" ]]; then
-			ftype='php'
-			file="${file}.${ftype}"
-		elif [[ -f "${file}.sh" ]]; then
-			ftype='sh'
-			file="${file}.${ftype}"
-		else
-			msg.die "File '$file' not found!"
+	# file not exist!
+	if [[ ! -f "$file" ]]; then
+		# look for likely executable script
+		sx="$(readlink -f "$(which "$(basename "$file")")")"
+#msg.warn "$sx"
+		if [[ -z $sx ]]; then
+			# locate or create
+			sx="$(basename "$file")"
+			arr=( $(locate -b "\\$sx") )
+			arr+=( "Create: ${file}"  )
+		 	select file in "${arr[@]}"; do 
+				[[ 'q0' == *"$REPLY"* ]] && return 1
+				[[ -z $file ]] && continue
+				break
+		 	done
+		 	[[ ${file:0:8} == 'Create: ' ]] && file="${file:8}"
 		fi
-	else
-		ext="${file##*.}"
-		if 		[[ "$ext" == 'php' ]];	then 
-			ftype='php'
-		elif 	[[ "$ext" == 'sh'	|| "$ext" == 'bash' ]]; then 
-			ftype='sh'
-		else
-			hd=$(head -n1 "$file")
-			hd=${hd%% *}
-			if [[ $hd == "#!$(which bash)" || $hd == "#!$(which sh)" || $hd == '#!/bin/bash' || $hd == '#!/bin/sh' ]]; then 
-				ftype='sh' 
-			elif [[ $hd == "#!$(which php)" || "${hd:0:2}" == '<?' ]]; then 
-				ftype='php' 
-			else 
-				msg.die "$file is not a bash or php script!"
-			fi
-		fi
+		file="$sx"	
 	fi
-
+	
+	ext="${file##*.}"
+	if 		[[ "$ext" == 'php' ]];	then 
+		ftype='php'
+	elif 	[[ "$ext" == 'sh'	|| "$ext" == 'bash' ]]; then 
+		ftype='sh'
+	else
+		ftype=$(textfiletype -t "$file")
+		[[ $ftype == 'text' || -z $ftype ]] && ftype='sh'
+#		hd=$(head -n1 "$file")
+#		hd=${hd%% *}
+#		if [[ $hd == "#!$(which bash)" || $hd == "#!$(which sh)" || $hd == '#!/bin/bash' || $hd == '#!/bin/sh' ]]; then 
+#			ftype='sh' 
+#		elif [[ $hd == "#!$(which php)" || "${hd:0:2}" == '<?' ]]; then 
+#			ftype='php' 
+#		else 
+#			msg.die "$file is not a bash or php script!"
+#		fi
+	fi
+	
+	# Edit it.
 	# shellcheck disable=2046
 	$EDITOR $( ((line)) && echo "+${line}" ) "$file"
 
+	[[ ! -f $file ]] && return 1
+
+	# syntax check
+	syntaxerr=0	
 	if [[ "${ftype}" == 'php' ]]; then
 		msg.info "$(php -l "${file}" 2>&1 | tee "$tmpfile")"
 		hd="$(head -n1 "$tmpfile")"
@@ -95,7 +108,6 @@ main() {
 			[[ -z "$l" ]] && line=0 || line=$l
 		fi
 	fi
-
 	if ((syntaxerr)); then
 		if ask.yn "Re-edit $file [$line]?"; then
 			# shellcheck disable=SC2046
@@ -104,6 +116,7 @@ main() {
 		fi
 	fi
 
+	# shellcheck
 	if ((shellcheck)) && [[ $ftype == 'sh' ]] ; then
 		if [[ -f "$file" ]]; then
 			local -- scdisable
